version: '3'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - .:/var/www/project
  #   networks:
  #     - danaischg-network

  # webserver:    
  #   image: nginx
  #   restart: unless-stopped
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - .:/var/www/project
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - app
  #   networks:
  #     - danaischg-network

  mysql:
    image: mysql:8.2.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: beatrice_password
      MYSQL_DATABASE: danaischg
      MYSQL_USER: beatrice
      MYSQL_PASSWORD: beatrice_password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - danaischg-network

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
    ports:
      - "8088:80"
    depends_on:
      - mysql
    networks:
      - danaischg-network

volumes:
  dbdata:
    driver: local

networks:
  danaischg-network:
    driver: bridge