controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

discount_index:
    path: /discount/index
    controller: App\Controller\DiscountController::index
homepage:  
    path: /  
    controller: App\Controller\MainController::index